### ISSUE TITLE
Request template design

### ISSUE THREAD

**Issue by harvanir** [harvanir/uji-beban#3]

**Comment by harvanir** [comment]
Propose 1:
```yml
uji-beban:
  requests:
    base:
      method: get
      path: http://localhost:8080/base
    base2:
      method: get
      path: http://localhost:8080/base2
```
